[project]
name = "uvdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=1.1.0",
    "langchain-openai>=1.1.0",
    "mcp-use>=1.4.1",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
